let islandFilter="Tutte", catFilter="Tutte", map, markers=[];
const colors={Spiaggia:"#2563eb",Attività:"#16a34a",Serata:"#9333ea",Base:"#f59e0b",Escursione:"#dc2626",Panorama:"#f97316",Pratico:"#64748b"};
const $=s=>document.querySelector(s);
function gmaps(p){return `https://www.google.com/maps/search/?api=1&query=${p[3]},${p[4]}`}
function gimages(p){return `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(p[2]+" "+p[0])}`}
function matches(p){return (islandFilter==="Tutte"||p[0]===islandFilter)&&(catFilter==="Tutte"||p[1]===catFilter||(catFilter==="Escursione"&&p[1]==="Panorama"))}
function card(p){return `<article class="card"><div class="badges"><span class="badge">${p[8]}</span><span class="badge">${p[0]}</span><span class="badge">${p[1]}</span><span class="badge">⭐ ${p[5]}/10</span></div><h3>${p[2]}</h3><div class="meta">💶 ${p[6]} · 🕐 ${p[7]}</div><p>${p[9]}</p><div class="actions"><a class="action" href="${gmaps(p)}" target="_blank">📍 Naviga</a><a class="action secondary" href="${gimages(p)}" target="_blank">📸 Foto</a></div></article>`}
function initMap(){if(map)return; map=L.map("leaflet").setView([28.35,-15.35],7); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map); renderMap();}
function renderMap(){if(!map)return; markers.forEach(m=>map.removeLayer(m)); markers=[]; const b=[]; PLACES.filter(matches).forEach(p=>{const icon=L.divIcon({className:"",html:`<div style="background:${colors[p[1]]||"#111"};width:20px;height:20px;border-radius:50%;border:3px solid white;box-shadow:0 2px 8px #0007"></div>`,iconSize:[20,20],iconAnchor:[10,10]}); const m=L.marker([p[3],p[4]],{icon}).addTo(map); m.bindPopup(`<b>${p[8]} ${p[2]}</b><br>${p[1]} · ⭐ ${p[5]}/10<br><a href="${gmaps(p)}" target="_blank">Apri navigazione</a>`); markers.push(m); b.push([p[3],p[4]]);}); if(b.length) map.fitBounds(b,{padding:[25,25]});}
function renderPlaces(){const q=($("#search")?.value||"").toLowerCase(); $("#placeCards").innerHTML=PLACES.filter(p=>(p[2]+" "+p[0]+" "+p[1]).toLowerCase().includes(q)).map(card).join("");}
function renderItinerary(){ $("#itineraryList").innerHTML=ITINERARY.map(d=>`<article class="card"><div class="badges"><span class="badge">${d[0]}</span><span class="badge">${d[1]}</span></div><h3>${d[2]}</h3><p>${d[3]}</p></article>`).join("");}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$("#"+b.dataset.view).classList.add("active"); if(b.dataset.view==="map"){setTimeout(()=>{initMap();map.invalidateSize();renderMap();},80)}});
document.querySelectorAll("[data-island]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-island]").forEach(x=>x.classList.remove("active"));b.classList.add("active");islandFilter=b.dataset.island;renderMap();});
document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-cat]").forEach(x=>x.classList.remove("active"));b.classList.add("active");catFilter=b.dataset.cat;renderMap();});
$("#search")?.addEventListener("input",renderPlaces);
const start=new Date("2026-08-09T00:00:00"); const days=Math.ceil((start-new Date())/86400000); $("#countdown").textContent=days>0?days:"0";
renderItinerary(); renderPlaces();
